### ISSUE TITLE
Depency on request isn't installed automatically

### ISSUE THREAD

**Issue by tr00st** [sganis/minirepo#1]
Really minor issue... When installing via pip, the dependency for requests is not picked up, so an error occurs when running. Looks like the line in setup.py is commented out - assuming accidentally?

from setup.py (approx #66):
 # install_requires=['requests'],

**Comment by jimsmith** [comment]
I am also getting an error with **No module named requests**

`pip install minirepo`
```
minirepo
Traceback (most recent call last):
  File "/home/ec2-user/.local/share/virtualenvs/pypi_minirepo-r1IsK5pf/bin/minirepo", line 7, in <module>
    from minirepo import main
  File "/home/ec2-user/.local/share/virtualenvs/pypi_minirepo-r1IsK5pf/lib/python2.7/site-packages/minirepo.py", line 13, in <module>
    import requests
ImportError: No module named requests
```

**Comment by sganis** [comment]
1. import requests 
```
pip install requests
```
2. try editing the minirepo.py file around line 300 and replace the ```mp.Pool(PROCESSES)``` line by ```mp.Pool(int(PROCESSES))```
