### ISSUE TITLE
Repo does not have a license

### ISSUE THREAD

**Issue by lobotmcj** [sganis/minirepo#10]
Hi, I'd like to use minirepo in one of my projects, but I'm hesitant to do so without a license for the repo.
Would you please consider adding one? Perhaps MIT or BSD?
Thank you!

**Comment by lobotmcj** [comment]
https://help.github.com/en/github/building-a-strong-community/adding-a-license-to-a-repository looks to be the easiest way to do this.

**Comment by lobotmcj** [comment]
added a pull request with an MIT license, but obviously use whatever license you think best, although a permissive license would be great (MIT, BSD3, Apache2, etc)

**Comment by sganis** [comment]
Accepted.
