### ISSUE TITLE
feature request: sync minirepo with only new/updated packages

### ISSUE THREAD

**Issue by gadh** [sganis/minirepo#6]
if i re-run the minirepo command, it downloads again all pkgs. it would be nice to download only the new/updated packages (maybe keepiong mongodb/sqlite db of downloaded pkgs internally)

+ also to delete old/obsolete/old versioned pkgs

**Comment by sganis** [comment]
That's exactly how it should work, check if you have permissions in the
config file

**Comment by CBtiger** [comment]
Just a note: I am seeing that it deleted packages and download them again. That seems to be due to updated data on the server. Anyway, it does not affect a lot of packages.

Generally updating an existing repository works fine. Also interrupting a download and continue another time works fine.
